services:
  localstack-lambda:
    image: localstack/localstack:latest
    container_name: localstack-lambda-athlete
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,s3
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PATH=${S3_PATH}
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
    volumes:
      - /d/dojo-athlete-mgmt-lambda/init-scripts:/etc/localstack/init/ready.d
      - //var/run/docker.sock:/var/run/docker.sock
      - /d/dojo-athlete-mgmt-lambda/app:/tmp/code