services:
  localstack-lambda-athlete:
    image: meu-localstack
    container_name: localstack-lambda-athlete
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,s3,apigateway
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PATH=${S3_PATH}
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - HOME=/tmp
    volumes:
      - ./init-scripts:/etc/localstack/init/ready.d
      - //var/run/docker.sock:/var/run/docker.sock
      - ./lambda_package.zip:/tmp/code/lambda_package.zip
      - ./athletes.parquet:/tmp/code/athletes.parquet